<H1><B>DAY 5</H1></B>

---



<H2>NumPy Array Copy vs View</H2>

---



<H3>The Difference Between Copy and View</H3>
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

<H3>COPY:</H3>

In [ ]:
import numpy as np

arr = np.array([2,4,6,8])
x = arr.copy()
arr[0] = 45
print(arr)
print(x)

[45  4  6  8]
[2 4 6 8]


<H3>VIEW:</H3>

In [ ]:
x = arr.view()
arr[0] = 45

print(arr)
print(x)

[45  4  6  8]
[45  4  6  8]


<H3>Make Changes in the VIEW:</H3>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


<h3>Check if Array Owns its Data</h3>
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
