<H1><B>DAY 7</H1></B>

---



<H2>NumPy Array Iterating</H2>

---



<H3>Iterating Arrays</H3>

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [2]:
import numpy as np

arr = np.array([1,1,1,2,2,2])

for x in arr:
  print(x)

1
1
1
2
2
2


<H3>Iterating 2-D Arrays</H3>

In [3]:
import numpy as np

arr = np.array([[1,0,3], [2,6,7]])

for x in arr:
  print(x)

[1 0 3]
[2 6 7]


In [5]:
print("Iterate on each scalar element of the 2-D array:")
for x in arr:
  for y in x:
    print(y)

Iterate on each scalar element of the 2-D array:
1
0
3
2
6
7


<h3>Iterating 3-D Arrays</h3>

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
print("Iterate down to the scalars:")
for x in arr:
  for y in x:
    for z in y:
      print(z)

Iterate down to the scalars:
1
2
3
4
5
6
7
8
9
10
11
12


<h3>Iterating Arrays Using nditer()</h3>
The function nditer() is a helping function that can be used from very basic to very advanced iterations.

In [8]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


<h3>Iterating Array With Different Data Types</h3>
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

In [12]:
import numpy as np

arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


<h3>Iterating With Different Step Size</h3>

In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


<h3>Enumerated Iteration Using ndenumerate()</h3>
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [14]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
