<H1><B>DAY 10

---



<H2>NUMPY ARRAY SEARCH

---



<H3>Searching Arrays</H3>

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [3]:

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


<H3>Search Sorted</H3>

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [4]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [5]:

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [6]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


<H2>NUMPY ARRAY SORT

---



<H3>Sorting Arrays</H3>

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [10]:
import numpy as np

arr = np.array([3, 2, 0, 1])


print(np.sort(arr))

[0 1 2 3]


In [11]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [12]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [13]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
