<H1><B>DAY 12

---



<H1><B>Random Numbers in NumPy

---


NumPy offers the random module to work with random numbers.

In [1]:
from numpy import random

x = random.randint(100)

print(x)

3


In [2]:
from numpy import random

x = random.rand()

print(x)

0.3462008066864183


In [3]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[21 40 35  0 59]


In [4]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[23 17  8 78 66]
 [11 99 27 12 76]
 [32  2 13 28 51]]


In [5]:
from numpy import random

x = random.rand(5)

print(x)

[0.53495326 0.21647435 0.47787612 0.94615189 0.94149046]


In [6]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.05515526 0.68637034 0.71853598 0.3947968  0.85772523]
 [0.34582223 0.91321581 0.66290396 0.96653666 0.01621133]
 [0.55387523 0.84078493 0.52353287 0.32179977 0.91802944]]


<H3>Generate Random Number From Array</H3>

The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 3 3 5]
 [5 3 7 5 3]
 [3 3 5 5 9]]
