<H1><B>DAY 6</H1></B>

---



<H2>NumPy Array Shape</H2>

---



NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [3]:
import numpy as np

arr = np.array([[1,3,5,7], [2,4,6,8]])

print(arr.shape)

(2, 4)


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


<H2>Reshaping arrays</H2>

---



Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [2]:
import numpy as np

arr = np.array([1,1,1,1,2,2,2,2,3,3,3,3])

newarr = arr.reshape(4, 3)
print("Reshape from 1D to 2D")
print(newarr)

Reshape from 1D to 2D
[[1 1 1]
 [1 2 2]
 [2 2 3]
 [3 3 3]]


In [3]:
newarr = arr.reshape(2, 3, 2)
print("Reshape from 1D to 3D")
print(newarr)

Reshape from 1D to 3D
[[[1 1]
  [1 1]
  [2 2]]

 [[2 2]
  [3 3]
  [3 3]]]


<h3>Check if the returned array is a copy or a view:</h3>

In [4]:
arr = np.array([1,1,1,1,2,2,2,2])

print(arr.reshape(2, 4).base)


[1 1 1 1 2 2 2 2]


<h3>Unknown Dimension</h3>

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
print("Convert 1D array with 8 elements to 3D array with 2x2 elements:")
print(newarr)

Convert 1D array with 8 elements to 3D array with 2x2 elements:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<h3>Flattening the arrays</h3>
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
