<H1><B>DAY 16

---



<H2>NumPy Set Operations

---



NumPy's unique() method to find unique elements from any array.

In [1]:
import numpy as np

arr = np.array([1, 1, 1, 2,2,3,3,3,4,5,5,5])

x = np.unique(arr)

print(x)

[1 2 3 4 5]


To find the unique values of two arrays, use the union1d() method.

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


To find only the values that are present in both arrays, use the intersect1d() method.

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [4]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [5]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
