<H1><B>DAY 12

---



<H2>NUMPY BUILT-IN FUNCTIONS

---



<H3>Addition</H3>

The add() function sums the content of two arrays, and return the results in a new array.

In [2]:
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


<h3>Subtraction</h3>
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [3]:
newarr = np.subtract(arr1, arr2)

print(newarr)

[-10 -10 -10 -10 -10 -10]


<h3>Multiplication</h3>
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [4]:
newarr = np.multiply(arr1, arr2)

print(newarr)

[200 231 264 299 336 375]


<h3>Division</h3>
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [5]:
newarr = np.divide(arr1, arr2)

print(newarr)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


<h3>Power</h3>
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [7]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 3])

newarr = np.power(arr1, arr2)

print(newarr)


[         1000       3200000     729000000 6553600000000          2500
        216000]


<h3>Remainder</h3>
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [8]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


<h3>Absolute Values</h3>
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [9]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


<h3>Logarithm</h3>

In [10]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
